GET http://localhost:3000

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/e7cc9b6a-a72e-47ae-939e-ec772975df60

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@provider.com.br"
}

###
POST http://localhost:3000/todos
Content-Type: application/json
x-user-id: eee618f2-2df8-4a62-848f-8d9d4cee7049

{
  "title": "Task #6"
}

###
POST http://localhost:3000/checkout
x-user-id: eee618f2-2df8-4a62-848f-8d9d4cee7049